[2022-07-21 17:38:21,841] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-07-21T17:38:19.421407+00:00 [queued]>
[2022-07-21 17:38:21,863] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-07-21T17:38:19.421407+00:00 [queued]>
[2022-07-21 17:38:21,865] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 17:38:21,868] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-21 17:38:21,871] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 17:38:21,890] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-07-21 17:38:19.421407+00:00
[2022-07-21 17:38:21,898] {standard_task_runner.py:52} INFO - Started process 7993 to run task
[2022-07-21 17:38:21,907] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2022-07-21T17:38:19.421407+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpdztp_ljs', '--error-file', '/tmp/tmpdzxwy4xi']
[2022-07-21 17:38:21,909] {standard_task_runner.py:80} INFO - Job 102: Subtask create_table
[2022-07-21 17:38:22,018] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table manual__2022-07-21T17:38:19.421407+00:00 [running]> on host e755cbaa46dc
[2022-07-21 17:38:22,165] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-21T17:38:19.421407+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-21T17:38:19.421407+00:00
[2022-07-21 17:38:22,180] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-21 17:38:22,185] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            )
        , parameters: None
[2022-07-21 17:38:22,188] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-07-21 17:38:22,204] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20220721T173819, start_date=20220721T173821, end_date=20220721T173822
[2022-07-21 17:38:22,277] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-21 17:38:22,347] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
