[2022-07-15 00:08:24,504] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-15T00:08:23.120585+00:00 [queued]>
[2022-07-15 00:08:24,512] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-15T00:08:23.120585+00:00 [queued]>
[2022-07-15 00:08:24,514] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 00:08:24,515] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-15 00:08:24,516] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 00:08:24,532] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-15 00:08:23.120585+00:00
[2022-07-15 00:08:24,540] {standard_task_runner.py:52} INFO - Started process 540 to run task
[2022-07-15 00:08:24,545] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-07-15T00:08:23.120585+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp4uvelctb', '--error-file', '/tmp/tmp_d0elyt6']
[2022-07-15 00:08:24,548] {standard_task_runner.py:80} INFO - Job 35: Subtask is_api_available
[2022-07-15 00:08:24,617] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-07-15T00:08:23.120585+00:00 [running]> on host 042af4b110d2
[2022-07-15 00:08:24,681] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-15T00:08:23.120585+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-15T00:08:23.120585+00:00
[2022-07-15 00:08:24,682] {http.py:97} INFO - Poking: api/
[2022-07-15 00:08:24,693] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-15 00:08:24,695] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-15 00:08:25,733] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-15 00:08:25,748] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220715T000823, start_date=20220715T000824, end_date=20220715T000825
[2022-07-15 00:08:25,771] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-15 00:08:25,848] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
