[2022-07-21 06:04:21,742] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-07-21T06:04:20.444697+00:00 [queued]>
[2022-07-21 06:04:21,750] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-07-21T06:04:20.444697+00:00 [queued]>
[2022-07-21 06:04:21,752] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 06:04:21,753] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-21 06:04:21,754] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 06:04:21,766] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-07-21 06:04:20.444697+00:00
[2022-07-21 06:04:21,770] {standard_task_runner.py:52} INFO - Started process 288 to run task
[2022-07-21 06:04:21,773] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2022-07-21T06:04:20.444697+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpoxun9fhz', '--error-file', '/tmp/tmpk647yzjf']
[2022-07-21 06:04:21,775] {standard_task_runner.py:80} INFO - Job 83: Subtask create_table
[2022-07-21 06:04:21,819] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table manual__2022-07-21T06:04:20.444697+00:00 [running]> on host b03e8595b275
[2022-07-21 06:04:21,874] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-21T06:04:20.444697+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-21T06:04:20.444697+00:00
[2022-07-21 06:04:21,882] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-21 06:04:21,886] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            )
        , parameters: None
[2022-07-21 06:04:21,888] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-07-21 06:04:21,898] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20220721T060420, start_date=20220721T060421, end_date=20220721T060421
[2022-07-21 06:04:21,949] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-21 06:04:21,994] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
