[2022-07-14 14:06:19,601] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-07-13T00:00:00+00:00 [queued]>
[2022-07-14 14:06:19,609] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-07-13T00:00:00+00:00 [queued]>
[2022-07-14 14:06:19,610] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-14 14:06:19,611] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-14 14:06:19,612] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-14 14:06:19,623] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-07-13 00:00:00+00:00
[2022-07-14 14:06:19,629] {standard_task_runner.py:52} INFO - Started process 8085 to run task
[2022-07-14 14:06:19,634] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2022-07-13T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmppmx9n304', '--error-file', '/tmp/tmpwe1onfbr']
[2022-07-14 14:06:19,636] {standard_task_runner.py:80} INFO - Job 15: Subtask create_table
[2022-07-14 14:06:19,739] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table scheduled__2022-07-13T00:00:00+00:00 [running]> on host 9d087153d2d5
[2022-07-14 14:06:19,932] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-13T00:00:00+00:00
[2022-07-14 14:06:19,947] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-14 14:06:19,967] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            )
        , parameters: None
[2022-07-14 14:06:19,969] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-07-14 14:06:19,987] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20220713T000000, start_date=20220714T140619, end_date=20220714T140619
[2022-07-14 14:06:20,058] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-14 14:06:20,146] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
