[2022-07-15 00:08:24,593] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-07-15T00:08:23.120585+00:00 [queued]>
[2022-07-15 00:08:24,601] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-07-15T00:08:23.120585+00:00 [queued]>
[2022-07-15 00:08:24,603] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 00:08:24,604] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-15 00:08:24,604] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 00:08:24,616] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-07-15 00:08:23.120585+00:00
[2022-07-15 00:08:24,625] {standard_task_runner.py:52} INFO - Started process 542 to run task
[2022-07-15 00:08:24,628] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2022-07-15T00:08:23.120585+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp631tjam6', '--error-file', '/tmp/tmp3kb3zd_b']
[2022-07-15 00:08:24,630] {standard_task_runner.py:80} INFO - Job 36: Subtask create_table
[2022-07-15 00:08:24,691] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table manual__2022-07-15T00:08:23.120585+00:00 [running]> on host 042af4b110d2
[2022-07-15 00:08:24,746] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-15T00:08:23.120585+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-15T00:08:23.120585+00:00
[2022-07-15 00:08:24,754] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-15 00:08:24,758] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            )
        , parameters: None
[2022-07-15 00:08:24,762] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-07-15 00:08:24,772] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20220715T000823, start_date=20220715T000824, end_date=20220715T000824
[2022-07-15 00:08:24,802] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-15 00:08:24,831] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
