[2022-07-15 00:57:58,806] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-15T00:57:57.623867+00:00 [queued]>
[2022-07-15 00:57:58,815] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-15T00:57:57.623867+00:00 [queued]>
[2022-07-15 00:57:58,816] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 00:57:58,817] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-15 00:57:58,818] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 00:57:58,829] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-15 00:57:57.623867+00:00
[2022-07-15 00:57:58,838] {standard_task_runner.py:52} INFO - Started process 3307 to run task
[2022-07-15 00:57:58,844] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-07-15T00:57:57.623867+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpbm8yfvql', '--error-file', '/tmp/tmpj2cypge7']
[2022-07-15 00:57:58,848] {standard_task_runner.py:80} INFO - Job 42: Subtask is_api_available
[2022-07-15 00:57:58,917] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-07-15T00:57:57.623867+00:00 [running]> on host 042af4b110d2
[2022-07-15 00:57:58,988] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-15T00:57:57.623867+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-15T00:57:57.623867+00:00
[2022-07-15 00:57:58,991] {http.py:97} INFO - Poking: api/
[2022-07-15 00:57:59,003] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-15 00:57:59,007] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-15 00:58:00,010] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-15 00:58:00,024] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220715T005757, start_date=20220715T005758, end_date=20220715T005800
[2022-07-15 00:58:00,063] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-15 00:58:00,109] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
