[2022-07-20 04:52:12,896] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 04:52:12,943] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-19T00:00:00+00:00 [queued]>
[2022-07-20 04:52:12,946] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 04:52:12,947] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-20 04:52:12,948] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-20 04:52:12,975] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-19 00:00:00+00:00
[2022-07-20 04:52:12,982] {standard_task_runner.py:52} INFO - Started process 72 to run task
[2022-07-20 04:52:12,987] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-07-19T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpfrz0sztb', '--error-file', '/tmp/tmpgbgsudlu']
[2022-07-20 04:52:13,003] {standard_task_runner.py:80} INFO - Job 55: Subtask is_api_available
[2022-07-20 04:52:13,120] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-07-19T00:00:00+00:00 [running]> on host 4800f8aada3e
[2022-07-20 04:52:13,280] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-19T00:00:00+00:00
[2022-07-20 04:52:13,283] {http.py:97} INFO - Poking: api/
[2022-07-20 04:52:13,304] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-20 04:52:13,309] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-20 04:52:13,721] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-20 04:52:13,741] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220719T000000, start_date=20220720T045212, end_date=20220720T045213
[2022-07-20 04:52:13,787] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-20 04:52:13,823] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
