[2022-07-22 00:03:38,130] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-21T00:00:00+00:00 [queued]>
[2022-07-22 00:03:38,141] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-21T00:00:00+00:00 [queued]>
[2022-07-22 00:03:38,142] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 00:03:38,143] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-22 00:03:38,145] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 00:03:38,158] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-21 00:00:00+00:00
[2022-07-22 00:03:38,165] {standard_task_runner.py:52} INFO - Started process 9082 to run task
[2022-07-22 00:03:38,172] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-07-21T00:00:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpu6dmuli9', '--error-file', '/tmp/tmpnw6v62pt']
[2022-07-22 00:03:38,174] {standard_task_runner.py:80} INFO - Job 118: Subtask is_api_available
[2022-07-22 00:03:38,301] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-07-21T00:00:00+00:00 [running]> on host e755cbaa46dc
[2022-07-22 00:03:38,393] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-21T00:00:00+00:00
[2022-07-22 00:03:38,396] {http.py:97} INFO - Poking: api/
[2022-07-22 00:03:38,405] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-22 00:03:38,411] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-22 00:03:40,469] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-22 00:03:40,490] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220721T000000, start_date=20220722T000338, end_date=20220722T000340
[2022-07-22 00:03:40,554] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 00:03:40,625] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
