[2022-07-15 00:08:22,121] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-14T00:00:00+00:00 [queued]>
[2022-07-15 00:08:22,131] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-14T00:00:00+00:00 [queued]>
[2022-07-15 00:08:22,132] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 00:08:22,134] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-15 00:08:22,135] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 00:08:22,146] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-14 00:00:00+00:00
[2022-07-15 00:08:22,155] {standard_task_runner.py:52} INFO - Started process 533 to run task
[2022-07-15 00:08:22,160] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-07-14T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp13bd40g0', '--error-file', '/tmp/tmpdorudqc0']
[2022-07-15 00:08:22,163] {standard_task_runner.py:80} INFO - Job 32: Subtask is_api_available
[2022-07-15 00:08:22,230] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-07-14T00:00:00+00:00 [running]> on host 042af4b110d2
[2022-07-15 00:08:22,290] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-14T00:00:00+00:00
[2022-07-15 00:08:22,293] {http.py:97} INFO - Poking: api/
[2022-07-15 00:08:22,306] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-15 00:08:22,309] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-15 00:08:23,279] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-15 00:08:23,293] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220714T000000, start_date=20220715T000822, end_date=20220715T000823
[2022-07-15 00:08:23,330] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-15 00:08:23,382] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
