[2022-07-22 00:14:20,976] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.story_user manual__2022-07-22T00:14:12.355527+00:00 [queued]>
[2022-07-22 00:14:20,986] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.story_user manual__2022-07-22T00:14:12.355527+00:00 [queued]>
[2022-07-22 00:14:20,987] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 00:14:20,988] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-22 00:14:20,989] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 00:14:21,000] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): story_user> on 2022-07-22 00:14:12.355527+00:00
[2022-07-22 00:14:21,006] {standard_task_runner.py:52} INFO - Started process 9747 to run task
[2022-07-22 00:14:21,010] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'story_user', 'manual__2022-07-22T00:14:12.355527+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpnu1ky80o', '--error-file', '/tmp/tmp8c8s18ci']
[2022-07-22 00:14:21,012] {standard_task_runner.py:80} INFO - Job 133: Subtask story_user
[2022-07-22 00:14:21,069] {task_command.py:369} INFO - Running <TaskInstance: user_processing.story_user manual__2022-07-22T00:14:12.355527+00:00 [running]> on host e755cbaa46dc
[2022-07-22 00:14:21,137] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=story_user
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T00:14:12.355527+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-22T00:14:12.355527+00:00
[2022-07-22 00:14:21,140] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2022-07-22 00:14:21,150] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-22 00:14:21,157] {python.py:173} INFO - Done. Returned value was: None
[2022-07-22 00:14:21,169] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=story_user, execution_date=20220722T001412, start_date=20220722T001420, end_date=20220722T001421
[2022-07-22 00:14:21,224] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 00:14:21,256] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
