[2022-07-21 06:04:16,584] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-20T00:00:00+00:00 [queued]>
[2022-07-21 06:04:16,591] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-20T00:00:00+00:00 [queued]>
[2022-07-21 06:04:16,592] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 06:04:16,593] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-21 06:04:16,594] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 06:04:16,604] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-20 00:00:00+00:00
[2022-07-21 06:04:16,610] {standard_task_runner.py:52} INFO - Started process 278 to run task
[2022-07-21 06:04:16,615] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-07-20T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpr5wqwm_y', '--error-file', '/tmp/tmp1wf2r_zz']
[2022-07-21 06:04:16,618] {standard_task_runner.py:80} INFO - Job 79: Subtask is_api_available
[2022-07-21 06:04:16,672] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-07-20T00:00:00+00:00 [running]> on host b03e8595b275
[2022-07-21 06:04:16,734] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-20T00:00:00+00:00
[2022-07-21 06:04:16,736] {http.py:97} INFO - Poking: api/
[2022-07-21 06:04:16,745] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-21 06:04:16,747] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-21 06:04:19,665] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-21 06:04:19,679] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220720T000000, start_date=20220721T060416, end_date=20220721T060419
[2022-07-21 06:04:19,733] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-21 06:04:19,767] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
