[2022-07-15 01:01:57,262] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-07-15T01:01:56.546523+00:00 [queued]>
[2022-07-15 01:01:57,277] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-07-15T01:01:56.546523+00:00 [queued]>
[2022-07-15 01:01:57,280] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 01:01:57,282] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-15 01:01:57,283] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 01:01:57,297] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-07-15 01:01:56.546523+00:00
[2022-07-15 01:01:57,304] {standard_task_runner.py:52} INFO - Started process 3556 to run task
[2022-07-15 01:01:57,309] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2022-07-15T01:01:56.546523+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpywvmok02', '--error-file', '/tmp/tmpza16bfl9']
[2022-07-15 01:01:57,312] {standard_task_runner.py:80} INFO - Job 48: Subtask create_table
[2022-07-15 01:01:57,377] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table manual__2022-07-15T01:01:56.546523+00:00 [running]> on host 042af4b110d2
[2022-07-15 01:01:57,450] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-15T01:01:56.546523+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-15T01:01:56.546523+00:00
[2022-07-15 01:01:57,461] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-15 01:01:57,467] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            )
        , parameters: None
[2022-07-15 01:01:57,471] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-07-15 01:01:57,484] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20220715T010156, start_date=20220715T010157, end_date=20220715T010157
[2022-07-15 01:01:57,522] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-15 01:01:57,555] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
