[2022-07-21 17:39:52,299] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-07-21T17:39:50.548594+00:00 [queued]>
[2022-07-21 17:39:52,312] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-07-21T17:39:50.548594+00:00 [queued]>
[2022-07-21 17:39:52,314] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 17:39:52,315] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-21 17:39:52,316] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-21 17:39:52,334] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-07-21 17:39:50.548594+00:00
[2022-07-21 17:39:52,341] {standard_task_runner.py:52} INFO - Started process 8092 to run task
[2022-07-21 17:39:52,351] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2022-07-21T17:39:50.548594+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpvmxhesdp', '--error-file', '/tmp/tmphkoxc42l']
[2022-07-21 17:39:52,354] {standard_task_runner.py:80} INFO - Job 109: Subtask create_table
[2022-07-21 17:39:52,426] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table manual__2022-07-21T17:39:50.548594+00:00 [running]> on host e755cbaa46dc
[2022-07-21 17:39:52,498] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-21T17:39:50.548594+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-21T17:39:50.548594+00:00
[2022-07-21 17:39:52,508] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-21 17:39:52,513] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            )
        , parameters: None
[2022-07-21 17:39:52,515] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-07-21 17:39:52,527] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20220721T173950, start_date=20220721T173952, end_date=20220721T173952
[2022-07-21 17:39:52,563] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-21 17:39:52,596] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
