[2022-07-15 00:08:22,094] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-07-14T00:00:00+00:00 [queued]>
[2022-07-15 00:08:22,101] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-07-14T00:00:00+00:00 [queued]>
[2022-07-15 00:08:22,102] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 00:08:22,104] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-15 00:08:22,105] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 00:08:22,114] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-07-14 00:00:00+00:00
[2022-07-15 00:08:22,123] {standard_task_runner.py:52} INFO - Started process 532 to run task
[2022-07-15 00:08:22,127] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2022-07-14T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpc60d_gkb', '--error-file', '/tmp/tmpky452lif']
[2022-07-15 00:08:22,129] {standard_task_runner.py:80} INFO - Job 33: Subtask create_table
[2022-07-15 00:08:22,203] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table scheduled__2022-07-14T00:00:00+00:00 [running]> on host 042af4b110d2
[2022-07-15 00:08:22,264] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-14T00:00:00+00:00
[2022-07-15 00:08:22,274] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-15 00:08:22,279] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            )
        , parameters: None
[2022-07-15 00:08:22,282] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-07-15 00:08:22,293] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20220714T000000, start_date=20220715T000822, end_date=20220715T000822
[2022-07-15 00:08:22,342] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-15 00:08:22,377] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
